AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-crud

  Sample SAM Template for serverless-crud

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: crud/
      Handler: read.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CRUD:
          Type: Api
          Properties:
            Path: /
            Method: get
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: crud/
      Handler: create.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CRUD:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
