   version: '3.8'
   services:
     dynamodb-local:
       command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
       image: "amazon/dynamodb-local:latest"
       container_name: dynamodb-local
       ports:
         - "8000:8000"
       volumes:
         - "./docker/dynamodb:/home/dynamodblocal/data"
       working_dir: /home/dynamodblocal
       networks:
         - lambda-local
     nginx-local:
       image: nginx:latest
       container_name: nginx-local
       ports:
         - "8001:80"
       volumes:
         - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
         - "./docker/nginx/html/:/usr/share/nginx/html/"
       networks:
         - lambda-local
   networks:
     lambda-local:
       external: true
